### ISSUE TITLE
Custom Object Detection Algorithm

### ISSUE THREAD

**Issue by SinghTejwinder** [nicrusso7/rex-gym#11]
Hi, I am looking to implement a custom object detection algorithm in rex gym. Can you please tell me how can I do so?

**Comment by nicrusso7** [comment]
You could create a new environment (I'd look at the `walk_env` probably) and put some random cubes and a ball on the plane as starting point. Then you could implement the object detection algorithm to detect the ball and write a reward function in order to learn how to reach the ball walking and steering. 

In the last update there is a model equipped with a 6DOF robotic arm - another possible application for that algorithm (e.g. grasp an object). I'll close this issue for now, feel free to reach me out again!
