### ISSUE TITLE
Considerations for 'Learning Quadrupedal Locomotion over Challenging Terrain' Paper

### ISSUE THREAD

**Issue by derektan95** [nicrusso7/rex-gym#24]
Hi @nicrusso7, 

Thank you for this fantastic effort in making this niche field open sourced. I was browsing through your source code as well as the research paper that inspired this work, and made some comparisons with more recent advancements in Deep Reinforcement Learning for robotic quadrupeds. 

1) How much effort is required to use this existing work to **train another robotic quadruped of an entirely different set of URDF**? For instance, how much changes do we need to do in order to train the Anymal Model C robot ([URDF here](https://github.com/ANYbotics/anymal_c_simple_description))?

2) If adapting the existing framework to accomodate other types of quadrupeds is simple, how much effort is required to **update the the approach to match current approaches**? For instance, the work as shown by the ETH Zurich's Robotics Systems Lab? (For one, they use Raisim while this repository is in the OpenAI Gym environment)
- [Learning Quadrupedal Locomotion over Challenging Terrain Youtube Video](https://www.youtube.com/watch?v=9j2a1oAHDL8)
- [Learning Quadrupedal Locomotion over Challenging Terrain Research Paper](https://arxiv.org/abs/2010.11251)

I am really excited about the prospect of Legged robots, and would love to invest the time to furthering the work in this repository. Looking forward to hearing from you!

Regards, 
Derek

**Comment by nicrusso7** [comment]
Hi, thanks for your message.

The envs are actually strictly tailored on the spotmicro model (trajectories references, simulation params and so on..) so may be complex reusing the very same code for any other robot platform.

In order to support different robot platforms, I’ve created the robot-gym repo where I’m trying to have a more generic approach. In this repo you can find 2 different robots implemented (check the k3lso branch).

Any feedback/contribution is welcome!

**Comment by nicrusso7** [comment]
Closing the issue. Feel free to continue this thread anyway.
