### ISSUE TITLE
OSError while running rex-gym policy

### ISSUE THREAD

**Issue by arcgolatkar** [nicrusso7/rex-gym#6]
![Anaconda Prompt (Anacondar) 06-07-2020 11_29_37](https://user-images.githubusercontent.com/47918300/86592870-d9a7f080-bfb1-11ea-8779-bf61ab73ce60.png)

i have followed the readme and installed rex-gym in a conda environment. While running "rex-gym policy --env gallop" i am getting an OSError: Cannot resume an existing run since the logging directory does not contain a configuration file. 

Please help me resolve the error.

**Comment by nicrusso7** [comment]
Hi, I see you are running it on a Windows machine, may I ask how are you installing the lib? could you try to install it from source? I just realized I didn't updated the latest lib version on PyPI (I'll do it with the next release - almost there), sorry about that.

**Comment by arcgolatkar** [comment]
I have installed it from source. Then tried using pypi on another environment . But both seem to give the same error.

**Comment by nicrusso7** [comment]
Thanks for pointing this out, I'll test the library on a Windows machine.

**Comment by arcgolatkar** [comment]
Here the problem was 'policy_dir' was pointing to 'd:\anacondar\envs\rex\rex_gym/policies/galloping/balanced' but there was no folder named 'rex_gym' in 'd:\anaconda\envs\rex' . So I manually copied the rex_gym folder there and it solved my problem. 
 Will be glad to  know if it's a environment problem or anything else.
Also , thanks for sharing the amazing work .

**Comment by nicrusso7** [comment]
Oh I see, thanks. It's weird as the setup.py should copy the lib modules into the env.. I also think there is an issue with the path as windows uses `\` while unix systems `/`. I'll fix this. Thanks!

**Comment by nicrusso7** [comment]
This bug was fixed with `0.2.7`. Feel free to reopen this issue if doesn't work for you.

**Comment by Gs-001** [comment]
I installed rex-gym from source inside a virtualenv
I am facing the same issue on running a per-trained model.

**Comment by DPR00** [comment]
I comment this in case someone would have the same problem:
I am using Ubuntu 18.04, 'venv' to create the environment, and the version 0.2.7. And I had the same problem that @arcgolatkar, but to solve the problem I copied manually the 'rex_gym' folder into '/path-to-env/rex/lib/python3.7/dist-packages'. In case you don't have the 'dist-packages', then you can create it by yourself. 
Anyways, if you are using another OS or Linux distro you can enter to the 'policy_player.py' file, located in 'playground' folder, and print the 'policy_dir' to see where you have to copy the 'rex_gym' folder. However, I think it should be a general solution for this.

Congrats @nicrusso7 for the project, it is an amazing tool and great papers :)

**Comment by datamomo** [comment]
If anyone is still struggling with this issue:
Based on the previous answer I have something to add/ a slightly different way: I am using Ubuntu 20.04. and as well 'venv' to create the environment. Version 0.2.7 as well. I faced the same problem as previously mentioned. For me the solution was changing just an index in the 'policy_player.py' script, located in 'playground' folder. So in line 15 I changed the '-1'  to '0'. 
The problem was that  site.getsitepackages() returns multiple paths and for me the wrong one was selected. The path selected was '/path-to-env/rex/lib/python3.7/dist-packages', but on the system I am running it has to be '/path-to-env/rex/lib/python3.7/site-packages'. This can be accomplished by just changing the index as mentioned. Hope this may help someone..

Thanks for publishing this great project! :)
